@token = 

### Login user
POST https://localhost:3000/users/login HTTP/1.1
Content-Type: application/json

{
	"username": "hsemog",
	"password": "password"
}

### Create user
POST https://localhost:3000/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
	"firstName": "Hugo",
	"lastName": "Melo",
	"username": "hsemog",
	"userStatus": 1,
	"email": "me@me.com",
	"password": "password",
	"phone": "12345"
}

### Update user
PATCH https://localhost:3000/users/hsemog HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
	"firstName": "John",
	"lastName": "Doe"
}

### Get user
GET https://localhost:3000/users/hsemog HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### Delete user
DELETE https://localhost:3000/users/hsemog HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
